language: node_js
node_js:
  - 0.12.5
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - bower install -f

script:
  - grunt --verbose
